# Generated by Django 6.0.1 on 2026-01-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_alter_project_image_alter_project_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='blogs', to='project.tag')),
            ],
        ),
    ]
