# Generated by Django 6.0.1 on 2026-01-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('rank', models.CharField(max_length=50, null=True)),
                ('rating', models.CharField(max_length=50, null=True)),
                ('solve', models.CharField(max_length=50, null=True)),
                ('contest', models.CharField(max_length=50, null=True)),
                ('priority', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
