# Generated by Django 6.0.1 on 2026-01-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cp',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cp',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
